# NeON build file (http://github.com/c4s4/neon)

default: release
extends: [buildir, archive, git, changelog]

targets:

  install:
    doc: Install scripts
    steps:
    - print: 'Installing Babel scripts'
    - $: 'sudo cp bin/* /opt/bin/'
    - $: 'sudo cp etc/* /etc/profile.d/'

  release:
    doc: Perform a release
    depends: [clean, archive]
    steps:
    - super:
