- build:       babel
  description: Build file for project Babel
  default:
  - clean
  - publish

- properties:
    name:        "babel"
    version:     "0.1.0"
    build_dir:   "build"
    article_md:  "readme.md"
    article_xml: "#{build_dir}/#{name}.xml"
    article_dir: "../sweetohm/pages"

- target:      xml
  description: Generate XML article
  script:
  - mkdir: :build_dir
  - "md2xml -a #{article_md} > #{article_xml}"

- target:      publish
  depends:     xml
  script:
  - cp:
      src:  :article_xml
      dest: :article_dir

- target:      release
  depends:     publish
  script:
  - 'git tag "RELEASE-#{version}" && git push --tag'

- target:      clean
  description: Clean generated files
  script:
  - rmdir: :build_dir
