# NeON build file (http://github.com/c4s4/neon)

properties:
  NAME: babel

extends:
- c4s4/build/buildir.yml
- c4s4/build/changelog.yml
- c4s4/build/git.yml
- c4s4/build/archive.yml

targets:

  install:
    doc: Install scripts
    steps:
    - print: 'Installing Babel scripts'
    - $: 'sudo cp bin/* /opt/bin/'
    - $: 'sudo cp etc/* /etc/profile.d/'

  release:
    doc: Perform a release
    depends: archive
    steps:
    - super:
