# NeON build file (http://github.com/c4s4/neon)

extends: [_git_master, _github]
default: release
configuration: '~/.neon/github.yml'
# GITHUB_TOKEN: 'abcdefghijklmnopqrstuvwxyz0123456789'

properties:
  SCRIPTS:
  - version
  - go-build
  - python-build
  - python-venv
  - vscodium-build
  CONFIGS:
  - app-dir.sh
  - golang.sh
  - java.sh
  - python.sh
  - vscodium.sh

targets:

  release:
    doc: Perform release
    depends: [last-tags, version, release-title, change-list]
    steps:
    - super:

  install:
    doc: Install scripts and configurations
    steps:
    - print: 'Installing Babel scripts'
    - for: script
      in:  =SCRIPTS
      do:
      - $: 'sudo cp bin/={script} /opt/bin/'
    - print: 'Installing Babel configs'
    - for: config
      in:  =CONFIGS
      do:
      - $: 'sudo cp etc/={config} /etc/profile.d/'
