# NeON build file (http://github.com/c4s4/neon)

default: release
extends: [_git_master]

properties:
  SCRIPTS:
  - version
  - go-build
  - perl-build
  - python-build
  - python-venv
  CONFIGS:
  - _app.sh
  - _opt.sh
  - golang.sh
  - java.sh
  - perl.sh
  - python.sh

targets:

  install:
    doc: Install scripts and configurations
    steps:
    - print: 'Installing Babel scripts'
    - for: script
      in:  =SCRIPTS
      do:
      - $: 'cp bin/={script} ~/bin/'
    - print: 'Installing Babel configs'
    - for: config
      in:  =CONFIGS
      do:
      - $: 'cp etc/={config} ~/etc/profile.d/'
