#!/bin/sh

set -e

TMPDIR=/tmp
USAGE="Usage: lua-build version"

VERSION=$1

if [ "${VERSION}" = -h ]; then
    echo ${USAGE}
    exit 0
fi
if [ "${VERSION}" = "" ]; then
    echo "You must pass version to build on command line"
    echo ${USAGE}
    exit 1
fi
if [ -d "/opt/lua/${VERSION}" ]; then
    echo "Destination directory "/opt/lua/${VERSION}" already exists"
    exit 1
fi


ARCHIVE="lua-${VERSION}.tar.gz"
URL="http://www.lua.org/ftp/${ARCHIVE}"

cd ${TMPDIR}
wget ${URL}

tar zxvf ${ARCHIVE}
cd "lua-${VERSION}"
make linux test
mkdir bin
cd bin
ln -sf ../src/lua .
cd ..

cd ..
sudo mv lua-${VERSION} /opt/lua/${VERSION}
rm ${ARCHIVE}

