#!/bin/sh

set -e

TMPDIR=/tmp
USAGE="Usage: rust-build version"

VERSION=$1

if [ "${VERSION}" = -h ]; then
    echo ${USAGE}
    exit 0
fi
if [ "${VERSION}" = "" ]; then
    echo "You must pass version to build on command line"
    echo ${USAGE}
    exit 1
fi
if [ -d "/opt/rust/${VERSION}" ]; then
    echo "Destination directory "/opt/rust/${VERSION}" already exists"
    exit 1
fi


ARCHIVE="rustc-${VERSION}-src.tar.gz"
URL="https://static.rust-lang.org/dist/${ARCHIVE}"

cd ${TMPDIR}
wget ${URL}

tar zxvf ${ARCHIVE}
cd "rust-${VERSION}"

./configure --prefix=/opt/rust/${VERSION}
make
sudo make install

cd ..
rm ${ARCHIVE}
rm -rf "rust-${VERSION}"
